export { backupFile, listBackups, restoreBackup } from './backup.js'
export type { Backup } from './backup.js'
export { detectProject, detectFramework } from './detect.js'
export { resolveTasks, resolveTaskStatuses } from './resolve.js'
export { applyTasks } from './apply.js'
export { fileExists, readFile, writeFile, resolvePath, readJson, readJsonIfExists, writeJson, copyFile, ensureDir } from './utils/fs.js'
export { readPackageJson, writePackageJson, hasDependency, getDependencyVersion, getNodeVersion } from './utils/pkg.js'
export { generateDiff, formatDiffHeader } from './utils/diff.js'
export type { FileDiff as CoreFileDiff } from './utils/diff.js'
export * as logger from './utils/logger.js'
export type { Task, TaskStatus, FileDiff } from './_base.js'
export type { ProjectProfile, Framework, Bundler, Router, Styling, PackageManager } from './detect.js'
