import type { ProjectProfile } from '@xtarterize/core'

export function renderPlopfile(profile: ProjectProfile): string {
  const generators: string[] = []
  
  if (profile.framework === 'react' || profile.framework === 'vue') {
    generators.push('component', 'hook', 'page', 'util')
  } else if (profile.framework === 'react-native') {
    generators.push('screen', 'component', 'hook', 'util')
  } else if (profile.framework === 'node') {
    generators.push('module', 'util')
  } else {
    generators.push('component', 'util')
  }
  
  return `// Auto-generated by xtarterize
// Generators: ${generators.join(', ')}

export default function (plop: any) {
${generators.map(g => `
  plop.setGenerator('${g}', {
    description: 'Create a new ${g}',
    prompts: [],
    actions: [],
  });`).join('\n')}
}
`
}
