import type { ProjectProfile } from '@xtarterize/core'
import { plopTemplates, type PlopTemplateKey } from './plop/index.js'

export { plopTemplates, type PlopTemplateKey }

export function getPlopTemplateFiles(profile: ProjectProfile): PlopTemplateKey[] {
	const files: PlopTemplateKey[] = []

	if (profile.framework === 'vue') {
		files.push('component.vue.hbs')
	} else {
		files.push('component.tsx.hbs')
	}

	files.push('util.ts.hbs', 'util.test.ts.hbs')

	if (profile.framework === 'node') {
		files.push('module.ts.hbs')
	}

	if (profile.framework === 'react-native') {
		files.push('screen.tsx.hbs', 'hook.ts.hbs')
	}

	if (profile.framework === 'react') {
		files.push('page.tsx.hbs', 'hook.ts.hbs')
	}

	return files
}

export function renderPlopfile(profile: ProjectProfile): string {
	const componentPath =
		profile.framework === 'vue'
			? 'src/components/{{pascalCase name}}.vue'
			: profile.framework === 'react-native'
				? 'src/components/{{pascalCase name}}.tsx'
				: 'src/components/{{pascalCase name}}/{{pascalCase name}}.tsx'
	const componentTemplateFile =
		profile.framework === 'vue' ? 'plop/component.vue.hbs' : 'plop/component.tsx.hbs'

	const pagePath =
		profile.bundler === 'nextjs'
			? 'app/{{kebabCase name}}/page.tsx'
			: 'src/pages/{{pascalCase name}}.tsx'

	const screenPath =
		profile.router === 'expo-router'
			? 'app/{{kebabCase name}}.tsx'
			: 'src/screens/{{pascalCase name}}Screen.tsx'

	const utilPath = profile.typescript
		? 'src/utils/{{kebabCase name}}.ts'
		: 'src/utils/{{kebabCase name}}.js'

	const modulePath = profile.typescript
		? 'src/{{kebabCase name}}/index.ts'
		: 'src/{{kebabCase name}}/index.js'

	return `// Auto-generated by xtarterize

export default function (plop: any) {
  const namePrompt = {
    type: 'input',
    name: 'name',
    message: 'Name',
    validate: (value: string) => value.trim().length > 0 || 'A name is required',
  }

  plop.setGenerator('component', {
    description: 'Create a reusable component',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${componentPath}',
        templateFile: '${componentTemplateFile}',
      },
    ],
  })

  plop.setGenerator('util', {
    description: 'Create a utility module',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${utilPath}',
        templateFile: 'plop/util.ts.hbs',
      },
      {
        type: 'add',
        path: 'src/utils/{{kebabCase name}}.test.ts',
        templateFile: 'plop/util.test.ts.hbs',
      },
    ],
  })
${profile.framework === 'node'
		? `
  plop.setGenerator('module', {
    description: 'Create a Node module',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${modulePath}',
        templateFile: 'plop/module.ts.hbs',
      },
    ],
  })
`
		: ''
}${profile.framework === 'react-native'
		? `
  plop.setGenerator('screen', {
    description: 'Create a React Native screen',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${screenPath}',
        templateFile: 'plop/screen.tsx.hbs',
      },
    ],
  })

  plop.setGenerator('hook', {
    description: 'Create a React hook',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: 'src/hooks/use{{pascalCase name}}.ts',
        templateFile: 'plop/hook.ts.hbs',
      },
    ],
  })
`
		: ''
}${profile.framework === 'react'
		? `
  plop.setGenerator('page', {
    description: 'Create an app page',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${pagePath}',
        templateFile: 'plop/page.tsx.hbs',
      },
    ],
  })

  plop.setGenerator('hook', {
    description: 'Create a React hook',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: 'src/hooks/use{{pascalCase name}}.ts',
        templateFile: 'plop/hook.ts.hbs',
      },
    ],
  })
`
		: ''
}}
`
}
