import type { ProjectProfile } from '@xtarterize/core'

export function renderPlopfile(profile: ProjectProfile): string {
	const componentPath =
		profile.framework === 'vue'
			? 'src/components/{{pascalCase name}}.vue'
			: profile.framework === 'react-native'
				? 'src/components/{{pascalCase name}}.tsx'
				: 'src/components/{{pascalCase name}}/{{pascalCase name}}.tsx'
	const pagePath =
		profile.bundler === 'nextjs'
			? 'app/{{kebabCase name}}/page.tsx'
			: 'src/pages/{{pascalCase name}}.tsx'
	const screenPath =
		profile.router === 'expo-router'
			? 'app/{{kebabCase name}}.tsx'
			: 'src/screens/{{pascalCase name}}Screen.tsx'
	const utilPath = profile.typescript
		? 'src/utils/{{kebabCase name}}.ts'
		: 'src/utils/{{kebabCase name}}.js'
	const modulePath = profile.typescript
		? 'src/{{kebabCase name}}/index.ts'
		: 'src/{{kebabCase name}}/index.js'
	const componentTemplate =
		profile.framework === 'vue'
			? `<script setup lang="ts">
defineProps<{
  title: string
}>()
</script>

<template>
  <section class="{{kebabCase name}}">
    <h2>{{ title }}</h2>
  </section>
</template>
`
			: `export interface {{pascalCase name}}Props {
  title: string
}

export function {{pascalCase name}}({ title }: {{pascalCase name}}Props) {
  return (
    <section className="{{kebabCase name}}">
      <h2>{title}</h2>
    </section>
  )
}
`

	return `// Auto-generated by xtarterize

export default function (plop: any) {
  const namePrompt = {
    type: 'input',
    name: 'name',
    message: 'Name',
    validate: (value: string) => value.trim().length > 0 || 'A name is required',
  }

  plop.setGenerator('component', {
    description: 'Create a reusable component',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${componentPath}',
        template: ${JSON.stringify(componentTemplate)},
      },
    ],
  })

  plop.setGenerator('util', {
    description: 'Create a utility module',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${utilPath}',
        template: 'export function {{camelCase name}}() {\\n  return null\\n}\\n',
      },
      {
        type: 'add',
        path: 'src/utils/{{kebabCase name}}.test.ts',
        template: "import { describe, expect, it } from 'vitest'\\nimport { {{camelCase name}} } from './{{kebabCase name}}'\\n\\ndescribe('{{camelCase name}}', () => {\\n  it('returns null by default', () => {\\n    expect({{camelCase name}}()).toBeNull()\\n  })\\n})\\n",
      },
    ],
  })

${
	profile.framework === 'node'
		? `  plop.setGenerator('module', {
    description: 'Create a Node module',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${modulePath}',
        template: 'export async function {{camelCase name}}() {\\n  return { ok: true }\\n}\\n',
      },
    ],
  })
`
		: ''
}
${
	profile.framework === 'react-native'
		? `  plop.setGenerator('screen', {
    description: 'Create a React Native screen',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${screenPath}',
        template: "import { Text, View } from 'react-native'\\n\\nexport default function {{pascalCase name}}Screen() {\\n  return (\\n    <View>\\n      <Text>{{titleCase name}}</Text>\\n    </View>\\n  )\\n}\\n",
      },
    ],
  })

  plop.setGenerator('hook', {
    description: 'Create a React hook',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: 'src/hooks/use{{pascalCase name}}.ts',
        template: 'import { useMemo } from \\'react\\'\\n\\nexport function use{{pascalCase name}}() {\\n  return useMemo(() => ({ ready: true }), [])\\n}\\n',
      },
    ],
  })
`
		: ''
}
${
	profile.framework === 'react'
		? `  plop.setGenerator('page', {
    description: 'Create an app page',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: '${pagePath}',
        template: "export default function {{pascalCase name}}Page() {\\n  return <main>{{titleCase name}}</main>\\n}\\n",
      },
    ],
  })

  plop.setGenerator('hook', {
    description: 'Create a React hook',
    prompts: [namePrompt],
    actions: [
      {
        type: 'add',
        path: 'src/hooks/use{{pascalCase name}}.ts',
        template: 'import { useMemo } from \\'react\\'\\n\\nexport function use{{pascalCase name}}() {\\n  return useMemo(() => ({ ready: true }), [])\\n}\\n',
      },
    ],
  })
`
		: ''
}
}
`
}
